const names = new Set([
  'left',
  'right',
  'brush',
  'eraser',
  'select',
  'move',
  'eyedropper',
  'hand',
  'fill',
  'undo',
  'redo',
  'plus',
  'minus',
  'open',
  'save',
  'export',
  'layers',
  'duplicate',
  'delete',
  'up',
  'down',
  'eye',
  'lock',
  'unlock',
  'transform',
  'adjust',
  'fit',
  'help',
  'settings',
  'close',
  'pen',
  'check',
  'image',
]);
export function icon(name: string, size = 18) {
  const symbol = names.has(name) ? name : 'brush';
  return `<img class="raster-icon" src="./icons/${symbol}.png" width="${size}" height="${size}" alt="" aria-hidden="true" draggable="false">`;
}
